extends: datarockets-base
rules:
  no-console: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
settings:
  import/core-modules:
    - hooks
  import/ignore:
    - models/index
    - controllers/v1/index
  import/resolver:
    node:
      extensions:
        - .js
      moduleDirectory:
        - node_modules
        - ./
