dry-run: null
hookfiles: ./**/*.hook.js
language: nodejs
sandbox: false
server: yarn dev:test
server-wait: 0
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 10
hooks-worker-connect-timeout: 10
hooks-worker-connect-retry: 100
hooks-worker-after-connect-wait: 10
hooks-worker-term-timeout: 10
hooks-worker-term-retry: 100
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: api-docs.apib
endpoint: 'http://127.0.0.1:6000'
